server:
  port: 8081
  servlet:
    context-path: /girl

girl:
  name: xiaoming-prod
  age: 18
  sex: man

cupSize: F
name: xiaohua-prod
age: 16
birthday: 2002-05-26 17:55:33
content: "name=${name}, cupSize=${cupSize}, name2=${girl.name}"